### ISSUE TITLE
Fatal error: Double free or corruption on Linux

### ISSUE THREAD

**Issue by TheUbuntuGuy** [clementine-player/Clementine#4643]
This bug exists in clementine_1.2.3-753-g8b19b30~trusty_amd64.deb but not in clementine_1.2.3-728-g763ee3d~trusty_amd64.deb.

I've tried reverting every single commit (of the possible 8) in between these 2 builds and the issue still exists, so I'm kind of stuck.

On Linux, if the playlist contains the moodbar column, creating moodbars on newly added tracks in the library will cause Clementine to crash. You cannot restart Clementine as it will just crash immediately upon trying to generate the moodbars. The only way I was able to start Clementine was to edit the DB externally and remove the items from the playlist so the moodbars weren't generated on startup.

This is 100% reproducable. I'm running Ubuntu 14.04 x64. Compiling with gcc 4.8.2.

This is the trace:

```
22:29:25.419 INFO  MoodbarLoader:143                Creating moodbar data for "/media/mark/storage/Music/P!nk/Funhouse/01.So What.flac" 
22:29:25.428 INFO  MoodbarLoader:143                Creating moodbar data for "/media/mark/storage/Music/P!nk/Funhouse/02.Sober.flac" 
22:29:25.436 INFO  MoodbarLoader:143                Creating moodbar data for "/media/mark/storage/Music/P!nk/Funhouse/03.I Don't Believe You.flac" 
22:29:25.441 INFO  MoodbarLoader:108                Loading cached moodbar data for "/media/mark/storage/Music/P!nk/Funhouse/04.One Foot Wrong.flac" 
22:29:25.442 INFO  MoodbarLoader:143                Creating moodbar data for "/media/mark/storage/Music/P!nk/Funhouse/05.Please Don't Leave Me.flac" 
[New Thread 0x7fff532d4700 (LWP 751)]
[New Thread 0x7fff52ad3700 (LWP 752)]
[New Thread 0x7fff520b4700 (LWP 753)]
22:29:25.458 INFO  MoodbarLoader:108                Loading cached moodbar data for "/media/mark/storage/Music/Linnea Dale/Good Goodbyes/01 Like a Feather.mp3" 
[New Thread 0x7fff518b3700 (LWP 754)]
[New Thread 0x7fff510b2700 (LWP 755)]
[New Thread 0x7fff508b1700 (LWP 757)]
22:29:25.460 INFO  MoodbarLoader:108                Loading cached moodbar data for "/media/mark/storage/Music/Linnea Dale/Good Goodbyes/02 High Hopes.mp3" 
[New Thread 0x7fff3bfff700 (LWP 759)]
22:29:25.461 INFO  MoodbarLoader:108                Loading cached moodbar data for "/media/mark/storage/Music/Linnea Dale/Good Goodbyes/03 If You Want Me To.mp3" 
22:29:25.469 INFO  MoodbarLoader:108                Loading cached moodbar data for "/media/mark/storage/Music/Linnea Dale/Good Goodbyes/04 Don't Think Twice.mp3" 
22:29:25.470 INFO  MoodbarLoader:108                Loading cached moodbar data for "/media/mark/storage/Music/Linnea Dale/Good Goodbyes/05 All The Things.mp3" 
22:29:25.471 INFO  MoodbarLoader:108                Loading cached moodbar data for "/media/mark/storage/Music/Linnea Dale/Good Goodbyes/06 Good Goodbye.mp3" 
22:29:25.472 INFO  MoodbarLoader:108                Loading cached moodbar data for "/media/mark/storage/Music/Linnea Dale/Good Goodbyes/07 Better Without You.mp3" 
*** Error in `/media/mark/storage/Projects/clementine-tug/bin/clementine': double free or corruption (out): 0x00007fff3413fa60 ***

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff518b3700 (LWP 754)]
0x00007ffff163fbb9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff163fbb9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff1642fc8 in __GI_abort () at abort.c:89
#2  0x00007ffff167ce14 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0x7ffff178b5a8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff16890ee in malloc_printerr (ptr=<optimized out>, str=0x7ffff178b6d8 "double free or corruption (out)", action=1)
    at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007ffff475808a in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#6  0x00007ffff4758cb8 in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#7  0x00007ffff475901f in fftw_mkplan_d () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#8  0x00007ffff4762512 in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#9  0x00007ffff47587bc in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#10 0x00007ffff4758a65 in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#11 0x00007ffff475901f in fftw_mkplan_d () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#12 0x00007ffff475dca2 in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#13 0x00007ffff47587bc in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#14 0x00007ffff4758a65 in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#15 0x00007ffff475901f in fftw_mkplan_d () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#16 0x00007ffff475db32 in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#17 0x00007ffff47587bc in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#18 0x00007ffff4758a65 in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#19 0x00007ffff475901f in fftw_mkplan_d () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#20 0x00007ffff47590b5 in fftw_mkplan_f_d () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#21 0x00007ffff475cca7 in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#22 0x00007ffff47587bc in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#23 0x00007ffff4758a65 in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#24 0x00007ffff475901f in fftw_mkplan_d () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#25 0x00007ffff47a0acf in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#26 0x00007ffff47587bc in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#27 0x00007ffff4758a65 in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#28 0x00007ffff48273da in ?? () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#29 0x00007ffff48275d4 in fftw_mkapiplan () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#30 0x00007ffff482b482 in fftw_plan_many_dft_r2c () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#31 0x00007ffff482aa14 in fftw_plan_dft_r2c () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#32 0x00007ffff482a973 in fftw_plan_dft_r2c_1d () from /usr/lib/x86_64-linux-gnu/libfftw3.so.3
#33 0x0000000000fc5723 in gst_fastspectrum_alloc_channel_data (spectrum=0x7fff54026ee0)
    at /media/mark/storage/Projects/clementine-tug/gst/moodbar/gstfastspectrum.cpp:140
#34 0x0000000000fc6397 in gst_fastspectrum_transform_ip (trans=0x7fff54026ee0, buffer=0x7fff340e5c10)
    at /media/mark/storage/Projects/clementine-tug/gst/moodbar/gstfastspectrum.cpp:428
#35 0x00007ffff4e63960 in ?? () from /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#36 0x00007ffff4e640a1 in ?? () from /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#37 0x00007ffff4b8cd08 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
---Type <return> to continue, or q <return> to quit---
#38 0x00007ffff4e642a9 in ?? () from /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#39 0x00007ffff4b8cd08 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#40 0x00007ffff4b7ee2b in gst_proxy_pad_chain_default () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#41 0x00007ffff4b8cd08 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#42 0x00007ffff4b7ee2b in gst_proxy_pad_chain_default () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#43 0x00007ffff4b8cd08 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#44 0x00007ffff55fa1fc in ?? () from /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0
#45 0x00007ffff55fa4b6 in ?? () from /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0
#46 0x00007ffff55feaac in gst_audio_decoder_finish_frame () from /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0
#47 0x00007fff3b5f5e01 in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstflac.so
#48 0x00007fffe833c40d in ?? () from /usr/lib/x86_64-linux-gnu/libFLAC.so.8
#49 0x00007fffe833e7d0 in FLAC__stream_decoder_process_single () from /usr/lib/x86_64-linux-gnu/libFLAC.so.8
#50 0x00007fff3b5f6672 in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstflac.so
#51 0x00007ffff55fbc73 in ?? () from /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0
#52 0x00007ffff55fc04b in ?? () from /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0
#53 0x00007ffff55fd036 in ?? () from /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0
#54 0x00007ffff4b8cd08 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#55 0x00007ffff4e46b09 in gst_base_parse_push_frame () from /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#56 0x00007ffff4e4a1c3 in gst_base_parse_finish_frame () from /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#57 0x00007fff520c2409 in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstaudioparsers.so
#58 0x00007ffff4e441e4 in ?? () from /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#59 0x00007ffff4e44752 in ?? () from /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#60 0x00007ffff4e48609 in ?? () from /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#61 0x00007ffff4bba549 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#62 0x00007ffff50f688c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#63 0x00007ffff50f5f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#64 0x00007ffff6aa1182 in start_thread (arg=0x7fff518b3700) at pthread_create.c:312
#65 0x00007ffff1703efd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by skrzepto** [comment]
I seem to have the same problem when I play long podcasts of ~2 hours long. It would just randomly close on me ~hour into the podcast. This is fairly reproducible. I wasn't sure if I needed to open a new Issue if mine is related to 
```
*** Error in `clementine': double free or corruption (fasttop): 0x00007fea58004950 ***
```

Let me know if I should open a new ticket.

```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.4 (Maipo)
```

Clementine Version
```
~ ⌚ 15:53:45
$ sudo yum list installed | grep clementine
clementine.x86_64                  1.3.1-1.el7.nux       @nux-dextop            
```

```
~ ⌚ 15:18:06
$ clementine
15:18:07.936 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Next"  
15:18:07.937 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Play"  
15:18:07.937 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Previous"  
15:18:08.042 WARN  unknown                          QPainter::begin: Paint device returned engine == 0, type: 2 
15:18:08.126 WARN  unknown                          Object::connect: No such signal QtSingleApplication::messageReceived(QByteArray) 
15:18:08.126 WARN  unknown                          Object::connect:  (sender name:   'clementine') 
15:18:08.126 WARN  unknown                          Object::connect:  (receiver name: 'MainWindow') 
*** Error in `clementine': double free or corruption (fasttop): 0x00007fea58004950 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c619)[0x7fea9194e619]
/lib64/libdbus-1.so.3(dbus_message_unref+0xc2)[0x7fea8d3effb2]
/lib64/libQtDBus.so.4(_ZN13QDBusArgumentD2Ev+0x29)[0x7fea934c54a9]
/lib64/libQtDBus.so.4(+0x2b70e)[0x7fea934a170e]
/lib64/libQtCore.so.4(+0x1a86f3)[0x7fea96c0d6f3]
/lib64/libQtDBus.so.4(+0x1a2cc)[0x7fea934902cc]
/lib64/libQtDBus.so.4(_ZN12QDBusMessageD1Ev+0x1f)[0x7fea934a4f6f]
/lib64/libQtDBus.so.4(+0x2bd36)[0x7fea934a1d36]
/lib64/libQtCore.so.4(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x20e)[0x7fea96bebbfe]
/lib64/libQtCore.so.4(+0x1b2d53)[0x7fea96c17d53]
/lib64/libglib-2.0.so.0(g_main_context_dispatch+0x159)[0x7fea95ea24c9]
/lib64/libglib-2.0.so.0(+0x4a818)[0x7fea95ea2818]
/lib64/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7fea95ea28cc]
/lib64/libQtCore.so.4(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x65)[0x7fea96c175d5]
/lib64/libQtCore.so.4(_ZN10QEventLoop13processEventsE6QFlagsINS_17ProcessEventsFlagEE+0x3f)[0x7fea96be765f]
/lib64/libQtCore.so.4(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x19d)[0x7fea96be79ad]
/lib64/libQtCore.so.4(_ZN7QThread4execEv+0xcf)[0x7fea96ade90f]
/lib64/libQtCore.so.4(+0x7c11f)[0x7fea96ae111f]
/lib64/libpthread.so.0(+0x7e25)[0x7fea96850e25]
/lib64/libc.so.6(clone+0x6d)[0x7fea919ca34d]
======= Memory map: ========
00400000-013ad000 r-xp 00000000 fd:02 20055754                           /usr/bin/clementine
015ac000-015ae000 r--p 00fac000 fd:02 20055754                           /usr/bin/clementine
015ae000-015b6000 rw-p 00fae000 fd:02 20055754                           /usr/bin/clementine
015b6000-015b9000 rw-p 00000000 00:00 0 
02ef0000-03cb0000 rw-p 00000000 00:00 0                                  [heap]
7fe9e8000000-7fe9e81ce000 rw-p 00000000 00:00 0 
7fe9e81ce000-7fe9ec000000 ---p 00000000 00:00 0 
7fe9ec000000-7fe9ec022000 rw-p 00000000 00:00 0 
7fe9ec022000-7fe9f0000000 ---p 00000000 00:00 0 
7fe9f0000000-7fe9f0035000 rw-p 00000000 00:00 0 
7fe9f0035000-7fe9f4000000 ---p 00000000 00:00 0 
7fe9f4000000-7fe9f4022000 rw-p 00000000 00:00 0 
7fe9f4022000-7fe9f8000000 ---p 00000000 00:00 0 
7fe9f8000000-7fe9f8040000 rw-p 00000000 00:00 0 
7fe9f8040000-7fe9fc000000 ---p 00000000 00:00 0 
7fe9fc000000-7fe9fc032000 rw-p 00000000 00:00 0 
7fe9fc032000-7fea00000000 ---p 00000000 00:00 0 
7fea0159b000-7fea015ba000 r-xp 00000000 fd:02 20062014                   /usr/lib64/libmad.so.0.2.1
7fea015ba000-7fea017b9000 ---p 0001f000 fd:02 20062014                   /usr/lib64/libmad.so.0.2.1
7fea017b9000-7fea017ba000 r--p 0001e000 fd:02 20062014                   /usr/lib64/libmad.so.0.2.1
7fea017ba000-7fea017bb000 rw-p 0001f000 fd:02 20062014                   /usr/lib64/libmad.so.0.2.1
7fea017bb000-7fea017bf000 r-xp 00000000 fd:02 20325129                   /usr/lib64/gstreamer-1.0/libgstmad.so
7fea017bf000-7fea019be000 ---p 00004000 fd:02 20325129                   /usr/lib64/gstreamer-1.0/libgstmad.so
7fea019be000-7fea019bf000 r--p 00003000 fd:02 20325129                   /usr/lib64/gstreamer-1.0/libgstmad.so
7fea019bf000-7fea019c0000 rw-p 00004000 fd:02 20325129                   /usr/lib64/gstreamer-1.0/libgstmad.so
7fea019c0000-7fea019c1000 ---p 00000000 00:00 0 
7fea019c1000-7fea021c1000 rw-p 00000000 00:00 0 
7fea021c1000-7fea021e0000 r-xp 00000000 fd:02 20322011                   /usr/lib64/gstreamer-1.0/libgstaudioparsers.so
7fea021e0000-7fea023df000 ---p 0001f000 fd:02 20322011                   /usr/lib64/gstreamer-1.0/libgstaudioparsers.so
7fea023df000-7fea023e0000 r--p 0001e000 fd:02 20322011                   /usr/lib64/gstreamer-1.0/libgstaudioparsers.so
7fea023e0000-7fea023e1000 rw-p 0001f000 fd:02 20322011                   /usr/lib64/gstreamer-1.0/libgstaudioparsers.so
7fea023e1000-7fea023e2000 ---p 00000000 00:00 0 
7fea023e2000-7fea02be2000 rw-p 00000000 00:00 0 
7fea02be2000-7fea02be5000 r-xp 00000000 fd:02 20322061                   /usr/lib64/gstreamer-1.0/libgstid3demux.so
7fea02be5000-7fea02de4000 ---p 00003000 fd:02 20322061                   /usr/lib64/gstreamer-1.0/libgstid3demux.so
7fea02de4000-7fea02de5000 r--p 00002000 fd:02 20322061                   /usr/lib64/gstreamer-1.0/libgstid3demux.so
7fea02de5000-7fea02de6000 rw-p 00003000 fd:02 20322061                   /usr/lib64/gstreamer-1.0/libgstid3demux.so
7fea02de6000-7fea02dfc000 r-xp 00000000 fd:02 20322131                   /usr/lib64/gstreamer-1.0/libgsttypefindfunctions.so
7fea02dfc000-7fea02ffb000 ---p 00016000 fd:02 20322131                   /usr/lib64/gstreamer-1.0/libgsttypefindfunctions.so
7fea02ffb000-7fea02ffc000 r--p 00015000 fd:02 20322131                   /usr/lib64/gstreamer-1.0/libgsttypefindfunctions.so
7fea02ffc000-7fea02ffe000 rw-p 00016000 fd:02 20322131                   /usr/lib64/gstreamer-1.0/libgsttypefindfunctions.so
7fea02ffe000-7fea02fff000 ---p 00000000 00:00 0 
7fea02fff000-7fea037ff000 rw-p 00000000 00:00 0 
7fea037ff000-7fea03800000 ---p 00000000 00:00 0 
7fea03800000-7fea04000000 rw-p 00000000 00:00 0 
7fea04000000-7fea04022000 rw-p 00000000 00:00 0 
7fea04022000-7fea08000000 ---p 00000000 00:00 0 
7fea08000000-7fea0c000000 rw-s 00000000 00:04 634859                     /memfd:pulseaudio (deleted)
7fea0c000000-7fea10000000 rw-s 00000000 00:04 35051                      /memfd:pulseaudio (deleted)
7fea10000000-7fea14000000 rw-s 00000000 00:04 638266                     /memfd:pulseaudio (deleted)
7fea14000000-7fea14021000 rw-p 00000000 00:00 0 
7fea14021000-7fea18000000 ---p 00000000 00:00 0 
7fea18000000-7fea1c000000 rw-s 00000000 00:04 638266                     /memfd:pulseaudio (deleted)
7fea1c000000-7fea1c051000 rw-p 00000000 00:00 0 
7fea1c051000-7fea20000000 ---p 00000000 00:00 0 
7fea20000000-7fea20021000 rw-p 00000000 00:00 0 
7fea20021000-7fea24000000 ---p 00000000 00:00 0 
7fea24147000-7fea24148000 ---p 00000000 00:00 0 
7fea24148000-7fea24948000 rw-p 00000000 00:00 0 
7fea24948000-7fea24949000 ---p 00000000 00:00 0 
7fea24949000-7fea25149000 rw-p 00000000 00:00 0 
7fea25149000-7fea2514a000 ---p 00000000 00:00 0 
7fea2514a000-7fea2594a000 rw-p 00000000 00:00 0 
7fea2594a000-7fea25950000 r-xp 00000000 fd:02 20065026                   /usr/lib64/libogg.so.0.8.0
7fea25950000-7fea25b4f000 ---p 00006000 fd:02 20065026                   /usr/lib64/libogg.so.0.8.0
7fea25b4f000-7fea25b50000 r--p 00005000 fd:02 20065026                   /usr/lib64/libogg.so.0.8.0
7fea25b50000-7fea25b51000 rw-p 00006000 fd:02 20065026                   /usr/lib64/libogg.so.0.8.0
7fea25b51000-7fea25b7d000 r-xp 00000000 fd:02 20065282                   /usr/lib64/libvorbis.so.0.4.6
7fea25b7d000-7fea25d7d000 ---p 0002c000 fd:02 20065282                   /usr/lib64/libvorbis.so.0.4.6[1]    3077 abort      clementine
```
