### ISSUE TITLE
Crash in the Android remote when clicking on "Set download folder" in settings

### ISSUE THREAD

**Issue by protz** [clementine-player/Clementine#4691]
I seem to be running version 10.1. The folder for downloaded music used to be /sdcard/0/ClementineMusic; after an upgrade, it switched to /storage/emulated/0/Android/data/de.qspool.clementineremote/files/Music ; when tapping on "Set download folder", the application crashes.

Furthermore, because it auto-connects when I restart the app, I was initially unable to submit the crash report (the dialog went away). Here's the stack trace.

== User Information ==
If you have any further information what you did to cause the crash or how to reproduce it, please write it here.

== Device Information ==

OS Version: 4.4.2 (3.4.0-2304514)
OS API Level: 19
Device: klteattactive
Model (and Product): SAMSUNG-SM-G870A (klteattactive)
App Version: v10.1 (479)

Max memory: 536870912
Current heap: 52887552
Heap available: 15144696
Native Heap: 6760944

== Stacktrace ==

java.lang.NullPointerException
at de.qspool.clementineremote.ui.settings.DefaultDirChooser.getDirectories(DefaultDirChooser.java:66)
at de.qspool.clementineremote.ui.settings.DefaultDirChooser.showAvailableDirectories(DefaultDirChooser.java:48)
at de.qspool.clementineremote.ui.settings.PreferencesBehaviorDownloads$1.onPreferenceClick(PreferencesBehaviorDownloads.java:55)
at android.preference.Preference.performClick(Preference.java:1048)
at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:229)
at android.widget.AdapterView.performItemClick(AdapterView.java:308)
at android.widget.AbsListView.performItemClick(AbsListView.java:1524)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3531)
at android.widget.AbsListView$3.run(AbsListView.java:4898)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5579)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
at dalvik.system.NativeStart.main(Native Method)

Let me know if I can be of further help. I can push an apk if needed.

Cheers,

Jonathan

**Comment by protz** [comment]
Closing since I didn't realize the remote was on a separate github repository.
