### ISSUE TITLE
Crash upon adding library or playing mp3

### ISSUE THREAD

**Issue by kpande** [clementine-player/Clementine#5033]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff76dcc94 in TagLib::RefCounter::count() const () from /usr/lib/x86_64-linux-gnu/libtag.so.1
(gdb) bt
#0  0x00007ffff76dcc94 in TagLib::RefCounter::count() const () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#1  0x00007ffff76d8142 in TagLib::ByteVector::detach() () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#2  0x00007ffff76d83d9 in TagLib::ByteVector::data() () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#3  0x00007ffff76db7c5 in TagLib::FileStream::readBlock(unsigned long) () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#4  0x00007ffff76da801 in TagLib::File::readBlock(unsigned long) () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#5  0x00007ffff76acb91 in TagLib::MPEG::File::findID3v2() () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#6  0x00007ffff76ace3c in TagLib::MPEG::File::read(bool, TagLib::AudioProperties::ReadStyle) () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#7  0x00007ffff76ad327 in TagLib::MPEG::File::File(char const*, bool, TagLib::AudioProperties::ReadStyle) () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#8  0x00007ffff770374e in TagLib::FileRef::create(char const*, bool, TagLib::AudioProperties::ReadStyle) () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#9  0x00007ffff77045c5 in TagLib::FileRef::FileRef(char const*, bool, TagLib::AudioProperties::ReadStyle) () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#10 0x000000000069d617 in TagLibFileRefFactory::GetFileRef(QString const&) ()
#11 0x000000000069ee25 in Song::InitFromFile(QString const&, int) ()
#12 0x000000000082f1bf in SongLoader::LoadLocal(QString const&, bool, bool) ()
#13 0x000000000082df35 in SongLoader::Load(QUrl const&) ()
#14 0x00000000007524ea in SongLoaderInserter::Load(Playlist*, int, bool, bool, QList<QUrl> const&) ()
#15 0x000000000071282e in Playlist::InsertUrls(QList<QUrl> const&, int, bool, bool) ()
#16 0x0000000000712585 in Playlist::dropMimeData(QMimeData const*, Qt::DropAction, int, int, QModelIndex const&) ()
#17 0x0000000000773bc3 in MainWindow::AddToPlaylist(QMimeData*) ()
#18 0x00000000007f7265 in ?? ()
#19 0x00007ffff70f866f in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#20 0x00000000007f9e47 in FileView::AddToPlaylist(QMimeData*) ()
#21 0x00000000007a165f in FileView::ItemDoubleClick(QModelIndex const&) ()
#22 0x00000000007f9c7e in ?? ()
#23 0x00007ffff70f866f in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#24 0x00007ffff668d425 in QAbstractItemView::doubleClicked(QModelIndex const&) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#25 0x00007ffff668d585 in QAbstractItemView::mouseDoubleClickEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#26 0x00007ffff61d25c2 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#27 0x00007ffff65800a6 in QFrame::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#28 0x00007ffff668c5db in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#29 0x00007ffff70e18c6 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#30 0x00007ffff61829bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#31 0x00007ffff618711b in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#32 0x00007ffff70e175e in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#33 0x00007ffff618382b in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#34 0x00007ffff61fe594 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#35 0x00007ffff61fd321 in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#36 0x00007ffff6224252 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#37 0x00007ffff3033355 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff3033688 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffff3033744 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007ffff7110326 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#41 0x00007ffff6223ece in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#42 0x00007ffff70e035f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#43 0x00007ffff70e05e8 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#44 0x00007ffff70e59e8 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#45 0x000000000067ae6b in main ()
(gdb) 
```

**Comment by Chocobozzz** [comment]
It's a taglib issue.
