### ISSUE TITLE
segfault on visualization start

### ISSUE THREAD

**Issue by pernatiy** [clementine-player/Clementine#5325]
### System information
- Operating System: Gentoo Linux
- Clementine version: clementine-1.3_rc1-r1::gentoo (essentially 1.3rc1 with patch https://github.com/clementine-player/Clementine/issues/5297) and build from git.

### Expected behaviour / actual behaviour
Start visualization / segfault

### Steps to reproduce the problem (only for bugs)
Start visualization using any method (menu, double-click on analyzer bar, etc)

---
Any attempt to start visualization lead to segfault. Interesting that I don't see clementine code in backtrace, still clementine is the only application that segfaults on opengl/egl usage.

Some build info:
```
dev-util/cmake:           3.5.1::gentoo
dev-util/pkgconfig:       0.29.1::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            5.3.0::gentoo
sys-devel/libtool:        2.4.6-r2::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.5::gentoo (virtual/os-headers)
sys-libs/glibc:           2.22-r4::gentoo
CFLAGS="-O2 -pipe -fomit-frame-pointer -march=ivybridge"
CXXFLAGS="-O2 -pipe -fomit-frame-pointer -march=ivybridge"
```

I don't have all debug symbols at the moment, but here is backtrace:
```
$ gdb -q $(which clementine) -ex r
Reading symbols from /usr/bin/clementine...(no debugging symbols found)...done.
Starting program: /usr/bin/clementine 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffdebd8700 (LWP 9045)]
[New Thread 0x7fffde3d7700 (LWP 9046)]
[New Thread 0x7fffddb6b700 (LWP 9047)]
[New Thread 0x7fffdd36a700 (LWP 9048)]
[New Thread 0x7fffcd5d6700 (LWP 9049)]
[New Thread 0x7fffccdd5700 (LWP 9050)]
[New Thread 0x7fffc3fff700 (LWP 9051)]
[New Thread 0x7fffc37fe700 (LWP 9056)]
[New Thread 0x7fffc25ed700 (LWP 9057)]
[New Thread 0x7fffc1dec700 (LWP 9058)]
[New Thread 0x7fffc15eb700 (LWP 9059)]
18:52:57.587 WARN  unknown                          QPainter::begin: Paint device returned engine == 0, type: 2 
18:52:57.750 WARN  unknown                          libpng warning: iCCP: known incorrect sRGB profile 
[New Thread 0x7fffc0dea700 (LWP 9060)]
[New Thread 0x7fff9fffd700 (LWP 9061)]
[New Thread 0x7fff9f7fc700 (LWP 9062)]
[New Thread 0x7fff9effb700 (LWP 9063)]
18:52:57.783 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
18:52:57.783 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
18:52:57.783 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
18:52:57.783 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
18:52:57.784 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
18:52:57.784 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
18:52:57.784 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
18:52:57.784 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
18:52:57.784 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
18:52:57.784 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
[New Thread 0x7fff9e7fa700 (LWP 9064)]
[New Thread 0x7fff9dff9700 (LWP 9065)]
[New Thread 0x7fff9d5c5700 (LWP 9066)]
18:52:58.135 WARN  unknown                          QSortFilterProxyModel: invalid inserted rows reported by source model 
18:52:58.135 WARN  unknown                          QSortFilterProxyModel: invalid inserted rows reported by source model 
[Thread 0x7fffc1dec700 (LWP 9058) exited]

Thread 1 "clementine" received signal SIGSEGV, Segmentation fault.
0x00007fffecca9189 in ?? () from /usr/lib64/libEGL.so.1
(gdb) bt
#0  0x00007fffecca9189 in ?? () from /usr/lib64/libEGL.so.1
#1  0x00007fffeccaadf3 in ?? () from /usr/lib64/libEGL.so.1
#2  0x00007fff7fbc550b in ?? () from /usr/lib64/dri/i965_dri.so
#3  0x00007fff7fbc5861 in ?? () from /usr/lib64/dri/i965_dri.so
#4  0x00007fff7fbc594b in ?? () from /usr/lib64/dri/i965_dri.so
#5  0x00007fff7fba7a36 in ?? () from /usr/lib64/dri/i965_dri.so
#6  0x00007fffecca36b5 in ?? () from /usr/lib64/libEGL.so.1
#7  0x00007fffecc9978c in eglMakeCurrent () from /usr/lib64/libEGL.so.1
#8  0x00007ffff32ffd9f in QEglContext::makeCurrent(void*) () from /usr/lib64/qt4/libQtGui.so.4
#9  0x00007ffff383c4ab in QGLContext::makeCurrent() () from /usr/lib64/qt4/libQtOpenGL.so.4
#10 0x00007ffff37dbc96 in QGLPaintDevice::beginPaint() () from /usr/lib64/qt4/libQtOpenGL.so.4
#11 0x00007ffff37dbe2e in ?? () from /usr/lib64/qt4/libQtOpenGL.so.4
#12 0x00007ffff3816dd3 in QGL2PaintEngineEx::begin(QPaintDevice*) () from /usr/lib64/qt4/libQtOpenGL.so.4
#13 0x00007ffff2dc7e3c in QPainter::begin(QPaintDevice*) () from /usr/lib64/qt4/libQtGui.so.4
#14 0x00007ffff2dc8848 in QPainter::QPainter(QPaintDevice*) () from /usr/lib64/qt4/libQtGui.so.4
#15 0x00007ffff32ae528 in QGraphicsView::paintEvent(QPaintEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#16 0x00007ffff2cc8940 in QWidget::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#17 0x00007ffff307630e in QFrame::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#18 0x00007ffff32ad5ff in QGraphicsView::viewportEvent(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#19 0x00007ffff6eb5f56 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#20 0x00007ffff2c70b1c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#21 0x00007ffff2c77ce6 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#22 0x00007ffff6eb5ddd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#23 0x00007ffff2cc2e87 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/qt4/libQtGui.so.4
#24 0x00007ffff2e9159d in QWidgetPrivate::repaint_sys(QRegion const&) () from /usr/lib64/qt4/libQtGui.so.4
#25 0x00007ffff2cb57d7 in QWidgetPrivate::syncBackingStore() () from /usr/lib64/qt4/libQtGui.so.4
#26 0x00007ffff2cc8a28 in QWidget::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#27 0x00007ffff37c712a in QGLWidget::event(QEvent*) () from /usr/lib64/qt4/libQtOpenGL.so.4
#28 0x00007ffff2c70b3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#29 0x00007ffff2c77ce6 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#30 0x00007ffff6eb5ddd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#31 0x00007ffff6eb9441 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib64/qt4/libQtCore.so.4
#32 0x00007ffff327cef8 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#33 0x00007ffff32860a9 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#34 0x00007ffff6ed0441 in QObject::event(QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#35 0x00007ffff3294b3b in QGraphicsScene::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#36 0x00007ffff2c70b3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#37 0x00007ffff2c77ce6 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#38 0x00007ffff6eb5ddd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#39 0x00007ffff6eb9441 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib64/qt4/libQtCore.so.4
#40 0x00007ffff6ee6f3e in ?? () from /usr/lib64/qt4/libQtCore.so.4
#41 0x00007ffff48dfea7 in g_main_dispatch (context=0x1051550) at /usr/src/debug/dev-libs/glib-2.48.0/glib-2.48.0/glib/gmain.c:3154
#42 g_main_context_dispatch (context=context@entry=0x1051550) at /usr/src/debug/dev-libs/glib-2.48.0/glib-2.48.0/glib/gmain.c:3769
#43 0x00007ffff48e0100 in g_main_context_iterate (context=context@entry=0x1051550, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /usr/src/debug/dev-libs/glib-2.48.0/glib-2.48.0/glib/gmain.c:3840
#44 0x00007ffff48e01ac in g_main_context_iteration (context=0x1051550, may_block=1) at /usr/src/debug/dev-libs/glib-2.48.0/glib-2.48.0/glib/gmain.c:3901
#45 0x00007ffff6ee70ae in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
#46 0x00007ffff2d1bad6 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#47 0x00007ffff6eb4611 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
#48 0x00007ffff6eb4985 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
#49 0x00007ffff6eba639 in QCoreApplication::exec() () from /usr/lib64/qt4/libQtCore.so.4
#50 0x00000000005da221 in main ()
```

**Comment by hatstand** [comment]
Looks like a dri/intel driver bug.
