### ISSUE TITLE
Clementine 1.3.0 crashed on quit

### ISSUE THREAD

**Issue by hotfloppy** [clementine-player/Clementine#5342]
### Before posting

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

- Operating System: Ubuntu 14.04.4 LTS, Trusty Tahr
- Clementine version: 1.3.0~trusty

### Expected behaviour / actual behaviour

- Expected: Clementine quit normally
- Actual: It crashed.

### Steps to reproduce the problem (only for bugs)

1. Run Clementine.
2. Go to Music > Quit

### Backtrace from gdb

```
(gdb) backtrace
#0  0x00007ffff12f7cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff12fb0d8 in __GI_abort () at abort.c:89
#2  0x0000000000ec115d in ?? ()
#3  0x00007ffff5b47bb1 in qt_message_output(QtMsgType, char const*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff5b47ff9 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff5b48804 in qFatal(char const*, ...) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007fffa33f30e3 in MenuProxy::removeMenu(QMenu*) () from /usr/lib/x86_64-linux-gnu/qt4/plugins/menubar/libtopmenu-qt4-module.so
#7  0x00007fffa33f2f1c in MenuProxy::removeAction(QAction*) () from /usr/lib/x86_64-linux-gnu/qt4/plugins/menubar/libtopmenu-qt4-module.so
#8  0x00007fffa33ef740 in TopMenuMenuBarImpl::removeAction(QAction*) () from /usr/lib/x86_64-linux-gnu/qt4/plugins/menubar/libtopmenu-qt4-module.so
#9  0x00007fffa33f2c1a in MenuProxy::eventFilter(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/qt4/plugins/menubar/libtopmenu-qt4-module.so
#10 0x00007ffff5c54646 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#11 0x00007ffff2e5fe0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#12 0x00007ffff2e664a0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#13 0x00007ffff5c544dd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#14 0x00007ffff2ea91fb in QWidget::removeAction(QAction*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#15 0x00007ffff2e58e95 in QAction::~QAction() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#16 0x00007ffff2e59039 in QAction::~QAction() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#17 0x00007ffff5c6b168 in QObjectPrivate::deleteChildren() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#18 0x00007ffff2eabd47 in QWidget::~QWidget() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#19 0x0000000000b69dad in MainWindow::~MainWindow() ()
#20 0x00000000009c7406 in main ()
(gdb)
```

### Error shown in gdb console

```
19:12:55.434 ERROR unknown                          ASSERT: "g_menu" in file menuproxy.cc, line 199 

Program received signal SIGABRT, Aborted.
0x00007ffff12f7cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Comment by hatstand** [comment]
This crash is caused by using the topmenu plugin.
