### ISSUE TITLE
Trying to play a Musepack(.mpc) file causes Clementine  to exit without an error

### ISSUE THREAD

**Issue by spiko** [clementine-player/Clementine#5453]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/) - NO, I tried it from git

### System information

Please provide information about your system and the version of Clementine used.

-Linux 4.6.0-1-686-pae #1 SMP Debian 4.6.2-2 (2016-06-25) i686 GNU/Linux
Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz

- Clementine version: 
Clementine 1.3 rc1
and
Clementine 1.3.1-222-gaf8ba89

### Expected behaviour / actual behaviour
Play the file successfully as it does .mp3 files
/
Clementine closes with message "Aborted" in console.

### Steps to reproduce the problem (only for bugs)
Enqueue an .mpc file. Double click it.

output from ./clementine --verbose:

...
14:49:24.112 DEBUG GnomeGlobalShortcutBackend:96    registered 
14:49:30.444 INFO  MoodbarLoader:147                Creating moodbar data for "/media/spiko/a23e37b1-adfb-4b24-92a2-2ea35b552437/Glasba/~-=[ -- e l e c t r 0 n 1 c -- ]=-~/[==Bobenj inj Bass(drum and bass)]/Quantum Mechanics CD2 (1998) Mixed (mpc)/(08) Science - Monochrome.mpc" 
14:49:30.446 DEBUG PlaylistBackend:294              Saving playlist 1 
14:49:30.497 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.503 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.503 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.504 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message stream-status 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message stream-status 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message stream-status 
14:49:30.505 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.506 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.506 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.506 DEBUG GstEnginePipeline:536            1 sync bus message stream-status 
14:49:30.506 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.506 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.506 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.557 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.557 DEBUG GstEnginePipeline:536            1 sync bus message stream-status 
14:49:30.557 DEBUG GstEnginePipeline:536            1 sync bus message state-changed 
14:49:30.573 DEBUG smart_playlists::Search:93       "SELECT ROWID,title, album, artist, albumartist, composer, track, disc, bpm, year, genre, comment, compilation, bitrate, samplerate, directory, filename, mtime, ctime, filesize, sampler, art_automatic, art_manual, filetype, playcount, lastplayed, rating, forced_compilation_on, forced_compilation_off, effective_compilation, skipcount, score, beginning, length, cue_path, unavailable, effective_albumartist, etag, performer, grouping, lyrics, originalyear, effective_originalyear FROM songs WHERE unavailable = 0 ORDER BY random() LIMIT 1" 
14:49:30.631 DEBUG GstEnginePipeline:510            1 bus message buffering 
14:49:30.638 DEBUG MainWindow:1477                  position 0 scrobble point 123 status 0 
14:49:30.850 DEBUG PlaylistBackend:294              Saving playlist 1 
Aborted

**Comment by spiko** [comment]
I tried disabling moodbar and moodbar generation without good results.

Here is the gdb output:

Reading symbols from ./clementine...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/src/c/clementine-player/bin/clementine 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
15:23:20.155 INFO  main:329                         Clementine 1.3.1-222-gaf8ba89 
[New Thread 0xacc0fb40 (LWP 2874)]
[New Thread 0xac40eb40 (LWP 2875)]
[New Thread 0xab8ffb40 (LWP 2876)]
[New Thread 0xaaeffb40 (LWP 2877)]
[New Thread 0xaa57fb40 (LWP 2878)]
[New Thread 0xa9d7eb40 (LWP 2879)]
15:23:21.146 DEBUG NetworkProxyFactory:49           Detected system proxy URLs: ("", "", "", "") 
[New Thread 0xa957db40 (LWP 2880)]
15:23:21.147 DEBUG WorkerPool<HandlerType>:281      Starting worker 0xa9d7dae0 "/usr/src/c/clementine-player/bin/clementine-tagreader" "/tmp/clementine_353559345" 
15:23:21.168 DEBUG WorkerPool<HandlerType>:281      Starting worker 0xa9d7dae0 "/usr/src/c/clementine-player/bin/clementine-tagreader" "/tmp/clementine_1338914123" 
15:23:21.180 INFO  main:48                          TagReader worker connecting to "/tmp/clementine_353559345" 
15:23:21.201 DEBUG WorkerPool<HandlerType>:301      Worker 0xab90dda8 connected to "/tmp/clementine_353559345" 
15:23:21.204 INFO  main:48                          TagReader worker connecting to "/tmp/clementine_1338914123" 
15:23:21.205 DEBUG WorkerPool<HandlerType>:301      Worker 0xab90e9d8 connected to "/tmp/clementine_1338914123" 
15:23:21.242 WARN  IconLoader:114                   Couldn't load icon "clementine-panel" 
15:23:21.255 WARN  IconLoader:114                   Couldn't load icon "clementine-panel-grey" 
[New Thread 0xa89ffb40 (LWP 2884)]
15:23:21.301 DEBUG GnomeGlobalShortcutBackend:52    registering 
[New Thread 0xa81b2b40 (LWP 2886)]
[New Thread 0xa793ab40 (LWP 2887)]
[New Thread 0xa7139b40 (LWP 2888)]
15:23:21.612 DEBUG MainWindow:227                   Starting 
15:23:21.777 WARN  unknown                          QPainter::begin: Paint device returned engine == 0, type: 2 
15:23:21.798 DEBUG CoverProviders:35                Registered cover provider "Amazon" 
15:23:21.798 DEBUG CoverProviders:35                Registered cover provider "MusicBrainz" 
15:23:21.798 DEBUG CoverProviders:35                Registered cover provider "last.fm" 
15:23:21.822 DEBUG MainWindow:298                   Initialising player 
15:23:21.826 DEBUG MainWindow:304                   Creating models 
15:23:21.932 INFO  Player:627                       Registered URL handler for "di" 
15:23:21.933 DEBUG InternetModel:136                Adding internet service: "DigitallyImported" 
15:23:21.958 DEBUG InternetModel:136                Adding internet service: "Icecast" 
15:23:21.975 DEBUG InternetModel:136                Adding internet service: "Jamendo" 
15:23:21.984 INFO  Player:627                       Registered URL handler for "jazzradio" 
15:23:21.985 DEBUG InternetModel:136                Adding internet service: "JazzRadio" 
15:23:21.987 INFO  Player:627                       Registered URL handler for "magnatune" 
15:23:21.996 DEBUG InternetModel:136                Adding internet service: "Magnatune" 
15:23:22.007 DEBUG InternetModel:136                Adding internet service: "Podcasts" 
15:23:22.016 INFO  Player:627                       Registered URL handler for "rockradio" 
15:23:22.016 DEBUG InternetModel:136                Adding internet service: "RockRadio" 
15:23:22.026 DEBUG InternetModel:136                Adding internet service: "SavedRadio" 
15:23:22.035 INFO  Player:627                       Registered URL handler for "radiotunes" 
15:23:22.035 DEBUG InternetModel:136                Adding internet service: "RadioTunes" 
15:23:22.044 INFO  Player:627                       Registered URL handler for "somafm" 
15:23:22.045 DEBUG InternetModel:136                Adding internet service: "SomaFM" 
15:23:22.054 INFO  Player:627                       Registered URL handler for "intergalacticfm" 
15:23:22.055 DEBUG InternetModel:136                Adding internet service: "Intergalactic FM" 
15:23:22.070 DEBUG InternetModel:136                Adding internet service: "SoundCloud" 
15:23:22.071 DEBUG SpotifyService:108               Spotify system blob path: "/usr/src/c/clementine-player/bin/clementine-spotifyblob" 
15:23:22.071 DEBUG SpotifyService:109               Spotify local blob path: "/home/user/.config/Clementine/spotifyblob/version16-32bit/blob" 
15:23:22.080 DEBUG InternetModel:136                Adding internet service: "Spotify" 
15:23:22.080 INFO  Player:627                       Registered URL handler for "subsonic" 
15:23:22.129 DEBUG InternetModel:136                Adding internet service: "Subsonic" 
15:23:22.258 INFO  Player:627                       Registered URL handler for "box" 
15:23:22.258 DEBUG InternetModel:136                Adding internet service: "Box" 
15:23:22.268 INFO  Player:627                       Registered URL handler for "dropbox" 
15:23:22.268 DEBUG InternetModel:136                Adding internet service: "Dropbox" 
15:23:22.281 INFO  Player:627                       Registered URL handler for "googledrive" 
15:23:22.281 DEBUG InternetModel:136                Adding internet service: "Google Drive" 
15:23:22.291 INFO  Player:627                       Registered URL handler for "seafile" 
15:23:22.291 DEBUG InternetModel:136                Adding internet service: "Seafile" 
15:23:22.301 WARN  unknown                          libpng warning: iCCP: known incorrect sRGB profile 
15:23:22.302 INFO  Player:627                       Registered URL handler for "skydrive" 
15:23:22.302 DEBUG InternetModel:136                Adding internet service: "OneDrive" 
15:23:22.313 INFO  Player:627                       Registered URL handler for "vk" 
15:23:22.314 DEBUG InternetModel:136                Adding internet service: "Vk.com" 
[New Thread 0x9e4ffb40 (LWP 2889)]
[New Thread 0x9dcfeb40 (LWP 2890)]
[New Thread 0x9d4fdb40 (LWP 2891)]
[New Thread 0x9ccfcb40 (LWP 2892)]
[New Thread 0x9c4fbb40 (LWP 2893)]
15:23:22.333 DEBUG MainWindow:323                   Creating UI 
[New Thread 0x9bcfab40 (LWP 2894)]
[New Thread 0x9b4f9b40 (LWP 2895)]
15:23:22.471 DEBUG MainWindow:868                   Creating equalizer 
15:23:22.473 DEBUG MainWindow:897                   Creating now playing widget 
15:23:22.613 INFO  NetworkRemote:83                 Network Remote deactivated 
15:23:22.621 DEBUG MainWindow:959                   Loading settings 
15:23:22.722 DEBUG MainWindow:1045                  Started 
15:23:22.787 INFO  DeviceManager:414                Device added: "/dev/sr0" 
15:23:22.990 DEBUG PlaylistBackend:294              Saving playlist 1 
15:23:23.502 DEBUG GnomeGlobalShortcutBackend:96    registered 
[Thread 0xa793ab40 (LWP 2887) exited]
[New Thread 0xa793ab40 (LWP 2896)]
15:23:30.283 DEBUG PlaylistBackend:294              Saving playlist 1 
15:23:30.400 DEBUG PlaylistBackend:294              Saving playlist 1 
[New Thread 0x99f0ab40 (LWP 2897)]
[New Thread 0x99709b40 (LWP 2898)]
[New Thread 0x90f07b40 (LWP 2899)]
[New Thread 0x90706b40 (LWP 2900)]
[New Thread 0x8ff05b40 (LWP 2901)]
[New Thread 0x8f704b40 (LWP 2902)]
15:23:30.684 DEBUG MainWindow:1477                  position 0 scrobble point 31 status 0 
[New Thread 0x8ef03b40 (LWP 2903)]

Thread 27 "task4" received signal SIGABRT, Aborted.
[Switching to Thread 0x8ef03b40 (LWP 2903)]
0xb7fd9dad in __kernel_vsyscall ()
(gdb) backtrace
#0  0xb7fd9dad in __kernel_vsyscall ()
#1  0xb32d7c19 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xb32d9117 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xb240dd58 in ?? () from /usr/lib/i386-linux-gnu/libavcodec.so.57
#4  0xb240de1f in avcodec_alloc_context3 () from /usr/lib/i386-linux-gnu/libavcodec.so.57
#5  0x9a4dd146 in ?? () from /usr/lib/i386-linux-gnu/gstreamer-1.0/libgstlibav.so
#6  0x9a4d3a7f in ?? () from /usr/lib/i386-linux-gnu/gstreamer-1.0/libgstlibav.so
#7  0xb7498423 in g_type_class_ref () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#8  0xb71cfe9e in gst_element_register () from /usr/lib/i386-linux-gnu/libgstreamer-1.0.so.0
#9  0x9a4d41ef in ?? () from /usr/lib/i386-linux-gnu/gstreamer-1.0/libgstlibav.so
#10 0x9a4c633b in ?? () from /usr/lib/i386-linux-gnu/gstreamer-1.0/libgstlibav.so
#11 0xb71f1e9f in ?? () from /usr/lib/i386-linux-gnu/libgstreamer-1.0.so.0
#12 0xb71f3c92 in ?? () from /usr/lib/i386-linux-gnu/libgstreamer-1.0.so.0
#13 0xb71f4412 in gst_plugin_load_file () from /usr/lib/i386-linux-gnu/libgstreamer-1.0.so.0
#14 0xb71f4915 in gst_plugin_load_by_name () from /usr/lib/i386-linux-gnu/libgstreamer-1.0.so.0
#15 0xb71f52a5 in gst_plugin_feature_load () from /usr/lib/i386-linux-gnu/libgstreamer-1.0.so.0
#16 0xb721b3aa in gst_type_find_factory_call_function () from /usr/lib/i386-linux-gnu/libgstreamer-1.0.so.0
#17 0xb7311748 in gst_type_find_helper_for_data () from /usr/lib/i386-linux-gnu/libgstbase-1.0.so.0
#18 0xb73118df in gst_type_find_helper_for_buffer () from /usr/lib/i386-linux-gnu/libgstbase-1.0.so.0
#19 0x9ac2e3d5 in ?? () from /usr/lib/i386-linux-gnu/gstreamer-1.0/libgstwavparse.so
#20 0x9ac2ec2a in ?? () from /usr/lib/i386-linux-gnu/gstreamer-1.0/libgstwavparse.so
#21 0x9ac35527 in ?? () from /usr/lib/i386-linux-gnu/gstreamer-1.0/libgstwavparse.so
#22 0xb72167ca in ?? () from /usr/lib/i386-linux-gnu/libgstreamer-1.0.so.0
#23 0xb7217767 in ?? () from /usr/lib/i386-linux-gnu/libgstreamer-1.0.so.0
#24 0xb73afa74 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#25 0xb73af01a in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#26 0xb756129a in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#27 0xb33910fe in clone () from /lib/i386-linux-gnu/libc.so.6
