### ISSUE TITLE
SIGABRT on startup with Qt5

### ISSUE THREAD

**Issue by Be-ing** [clementine-player/Clementine#5968]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/) (N/A, compiled from Git)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Fedora 27
- Clementine version: qt5 git branch, commit abf390729a42890cc62e6700f50cb63a2ac8211d

### Expected behaviour / actual behaviour
run Clementine

### Steps to reproduce the problem (only for bugs)
Compile qt5 branch on Fedora 27. Run clementine binary. I had previously run Clementine 1.3.1 from the Fedora package.

GDB backtrace:
```be@localhost ~/s/Clementine> gdb ./clementine 
GNU gdb (GDB) Fedora 8.0.1-33.fc27
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./clementine...done.
(gdb) run
Starting program: /home/be/sw/Clementine/clementine 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.26-21.fc27.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffddafd700 (LWP 5922)]
[New Thread 0x7fffd4ae1700 (LWP 5923)]
[New Thread 0x7fffcffff700 (LWP 5924)]
[New Thread 0x7fffcf7fe700 (LWP 5925)]
[New Thread 0x7fffce76c700 (LWP 5926)]
[New Thread 0x7fffcdcc3700 (LWP 5931)]
[New Thread 0x7fffcd4c2700 (LWP 5932)]

Thread 1 "clementine" received signal SIGABRT, Aborted.
0x00007ffff0aae66b in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install GConf2-3.2.6-19.fc27.x86_64 adwaita-qt5-1.0-3.fc27.x86_64 at-spi2-atk-2.26.1-1.fc27.x86_64 at-spi2-core-2.26.2-1.fc27.x86_64 atk-2.26.1-1.fc27.x86_64 bzip2-libs-1.0.6-24.fc27.x86_64 cairo-1.15.10-1.fc27.x86_64 cairo-gobject-1.15.10-1.fc27.x86_64 cryptopp-5.6.3-10.fc27.x86_64 dbus-glib-0.108-4.fc27.x86_64 dbus-libs-1.12.0-1.fc27.x86_64 dconf-0.26.1-1.fc27.x86_64 expat-2.2.5-1.fc27.x86_64 fftw-libs-double-3.3.5-7.fc27.x86_64 flac-libs-1.3.2-4.fc27.x86_64 fontconfig-2.12.6-4.fc27.x86_64 freetype-2.8-7.fc27.x86_64 gdk-pixbuf2-2.36.11-1.fc27.x86_64 glib2-2.54.2-1.fc27.x86_64 graphite2-1.3.10-3.fc27.x86_64 gsm-1.0.17-3.fc27.x86_64 gstreamer1-1.12.4-1.fc27.x86_64 gstreamer1-plugins-base-1.12.4-1.fc27.x86_64 gtk3-3.22.26-2.fc27.x86_64 gvfs-client-1.34.1-1.fc27.x86_64 harfbuzz-1.4.8-1.fc27.x86_64 libGLEW-2.0.0-4.fc27.x86_64 libICE-1.0.9-11.fc27.x86_64 libSM-1.2.2-7.fc27.x86_64 libX11-1.6.5-4.fc27.x86_64 libX11-xcb-1.6.5-4.fc27.x86_64 libXau-1.0.8-9.fc27.x86_64 libXcomposite-0.4.4-11.fc27.x86_64 libXcursor-1.1.14-10.fc27.x86_64 libXdamage-1.1.4-11.fc27.x86_64 libXext-1.3.3-7.fc27.x86_64 libXfixes-5.0.3-4.fc27.x86_64 libXi-1.7.9-4.fc27.x86_64 libXinerama-1.1.3-9.fc27.x86_64 libXrandr-1.5.1-4.fc27.x86_64 libXrender-0.9.10-4.fc27.x86_64 libXtst-1.2.3-4.fc27.x86_64 libasyncns-0.8-13.fc27.x86_64 libblkid-2.30.2-1.fc27.x86_64 libcap-2.25-7.fc27.x86_64 libcdio-0.94-4.fc27.x86_64 libchromaprint-1.2-8.fc27.x86_64 libdatrie-0.2.9-6.fc27.x86_64 libepoxy-1.4.3-3.fc27.x86_64 libffi-3.1-14.fc27.x86_64 libgcc-7.2.1-2.fc27.x86_64 libgcrypt-1.8.1-3.fc27.x86_64 libglvnd-1.0.0-1.fc27.x86_64 libglvnd-glx-1.0.0-1.fc27.x86_64 libgpg-error-1.27-3.fc27.x86_64 libicu-57.1-9.fc27.x86_64 libmount-2.30.2-1.fc27.x86_64 libmtp-1.1.14-1.fc27.x86_64 libogg-1.3.2-8.fc27.x86_64 libpng-1.6.31-1.fc27.x86_64 libselinux-2.7-3.fc27.x86_64 libsndfile-1.0.28-6.fc27.x86_64 libstdc++-7.2.1-2.fc27.x86_64 libthai-0.1.25-4.fc27.x86_64 libusbx-1.0.21-4.fc27.x86_64 libuuid-2.30.2-1.fc27.x86_64 libvorbis-1.3.5-4.fc27.x86_64 libwayland-client-1.14.0-2.fc27.x86_64 libwayland-cursor-1.14.0-2.fc27.x86_64 libxcb-1.12-5.fc27.x86_64 libxkbcommon-0.7.1-5.fc27.x86_64 libxkbcommon-x11-0.7.1-5.fc27.x86_64 lz4-libs-1.8.0-1.fc27.x86_64 mesa-libGLU-9.0.0-13.fc27.x86_64 mesa-libwayland-egl-17.2.4-3.fc27.x86_64 openssl-libs-1.1.0g-1.fc27.x86_64 orc-0.4.28-1.fc27.x86_64 pango-1.40.14-1.fc27.x86_64 pcre-8.41-4.fc27.x86_64 pcre2-10.30-5.fc27.x86_64 pcre2-utf16-10.30-5.fc27.x86_64 pixman-0.34.0-4.fc27.x86_64 protobuf-3.3.1-2.fc27.x86_64 pulseaudio-libs-11.1-7.fc27.x86_64 qgnomeplatform-0.3-5.fc27.x86_64 qt5-qtbase-5.9.2-6.fc27.x86_64 qt5-qtbase-gui-5.9.2-6.fc27.x86_64 qt5-qtx11extras-5.9.2-1.fc27.x86_64 sqlite-libs-3.20.1-1.fc27.x86_64 systemd-libs-234-9.fc27.x86_64 taglib-1.11.1-5.fc27.x86_64 tcp_wrappers-libs-7.6-87.fc27.x86_64 xcb-util-0.4.0-8.fc27.x86_64 xcb-util-image-0.4.0-8.fc27.x86_64 xcb-util-keysyms-0.4.0-6.fc27.x86_64 xcb-util-renderutil-0.3.9-9.fc27.x86_64 xcb-util-wm-0.4.1-11.fc27.x86_64 xz-libs-5.2.3-4.fc27.x86_64 zlib-1.2.11-4.fc27.x86_64
(gdb) bt
#0  0x00007ffff0aae66b in raise () at /lib64/libc.so.6
#1  0x00007ffff0ab0381 in abort () at /lib64/libc.so.6
#2  0x0000000000ea576a in logging::MessageHandler(QtMsgType, QMessageLogContext const&, QString const&) ()
#3  0x00007ffff201bc57 in qt_message_print(QtMsgType, QMessageLogContext const&, QString const&) () at /lib64/libQt5Core.so.5
#4  0x00007ffff201bd38 in qt_message(QtMsgType, QMessageLogContext const&, char const*, __va_list_tag*) () at /lib64/libQt5Core.so.5
#5  0x00007ffff201d61e in QMessageLogger::fatal(char const*, ...) const () at /lib64/libQt5Core.so.5
#6  0x00000000009917d2 in Database::ExecSongTablesCommands(QSqlDatabase&, QStringList const&, QStringList const&) ()
#7  0x00000000009912b3 in Database::ExecSchemaCommands(QSqlDatabase&, QString const&, int, bool) ()
#8  0x000000000099117d in Database::ExecSchemaCommandsFromFile(QSqlDatabase&, QString const&, int, bool) ()
#9  0x000000000099090c in Database::UpdateDatabaseSchema(int, QSqlDatabase&) ()
#10 0x000000000098fa4c in Database::UpdateMainSchema(QSqlDatabase*) ()
#11 0x000000000098f32f in Database::Connect() ()
#12 0x000000000098e79d in Database::Database(Application*, QObject*, QString const&) ()
#13 0x000000000097c354 in ApplicationImpl::ApplicationImpl(Application*)::{lambda()#2}::operator()() const ()
#14 0x0000000000980301 in std::_Function_handler<Database* (), ApplicationImpl::ApplicationImpl(Application*)::{lambda()#2}>::_M_invoke(std::_Any_data const&) ()
#15 0x00000000009871a8 in std::function<Database* ()>::operator()() const ()
#16 0x00000000009840cc in Lazy<Database>::CheckInitialised() const ()
#17 0x000000000097fcf6 in Lazy<Database>::get() const ()
#18 0x000000000097bdd0 in Application::database() const ()
#19 0x0000000000a4a211 in Library::Library(Application*, QObject*) ()
#20 0x000000000097c8cb in ApplicationImpl::ApplicationImpl(Application*)::{lambda()#14}::operator()() const ()
#21 0x0000000000982029 in std::_Function_handler<Library* (), ApplicationImpl::ApplicationImpl(Application*)::{lambda()#14}>::_M_invoke(std::_Any_data const&) ()
#22 0x0000000000987542 in std::function<Library* ()>::operator()() const ()
#23 0x00000000009842ca in Lazy<Library>::CheckInitialised() const ()
#24 0x000000000097fdc8 in Lazy<Library>::get() const ()
#25 0x000000000097beac in Application::library() const ()
#26 0x000000000097b927 in Application::Application(QObject*) ()
#27 0x0000000000978f70 in main ()
(gdb)
```

**Comment by garciaadrian** [comment]
Try using a new database

**Comment by Be-ing** [comment]
```
be@localhost ~> rm -r .config/Clementine-qt5/
be@localhost ~> clementine
fish: “clementine” terminated by signal SIGABRT (Abort)
```
