### ISSUE TITLE
 LibraryWatcher::ScanSubdirectory infinite recursion 

### ISSUE THREAD

**Issue by ChaosYoda** [clementine-player/Clementine#6049]
- Operating System: arch linux 
- Clementine version: 1.3.1 and latest source 

Clemetine gets stuck at 75% scanning my library, I have made some progress tracking down where the issue is: 
[tazy@boom Donna Burke]$ ls -la
total 2816
drwxr-xr-x 1 tazy users       0 Aug 25  2016  .
drwxr-xr-x 1 tazy users 2883584 May  4 10:53  ..
drwxr-xr-x 1 tazy users       0 Aug 25  2016 ''$'\343\200\212\345\212\250\346\204\237\346\226\260\345\212\277\345\212\233\343\200\213'

for some reason this folder causes the infinite recursion 
folder name "《动感新势力》/"

**Comment by Tazmain** [comment]
seems the issue is caused by 
[tazy@boom Donna Burke]$ ls -la
total 2816
drwxr-xr-x 1 tazy users       0 Aug 25  2016  .
drwxr-xr-x 1 tazy users 2883584 May  4 10:53  ..
drwxr-xr-x 1 tazy users       0 Aug 25  2016 ''$'\343\200\212\345\212\250\346\204\237\346\226\260\345\212\277\345\212\233\343\200\213'

**Comment by Tazmain** [comment]
GDB output 
22:15:54.850 DEBUG TagReader:130                    Reading tags from "/mnt/MUSIC/Music/Donati & Amato/Dance Floor Summer Hits 2012/17 Falling.mp3" 
22:15:54.850 DEBUG MessageReply<MessageType>:90     Releasing ID 26135 (finished) 
22:15:54.850 DEBUG _MessageReplyBase:26             Acquired ID 26135 
22:15:54.851 DEBUG LibraryWatcher:384               "/mnt/MUSIC/Music/Donati & Amato/Dance Floor Summer Hits 2012/17 Falling.mp3" created 
22:15:54.851 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke" subdir path 

40k lines of the same output cut here 


22:16:02.592 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.592 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.592 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.592 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.592 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.592 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.593 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.593 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.593 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.593 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.593 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.593 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.593 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.593 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.594 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.594 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.594 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.594 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.594 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.594 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.595 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.595 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.595 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.595 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.595 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.595 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.595 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.595 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.596 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.596 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.596 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.596 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.596 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.596 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  
22:16:02.597 DEBUG LibraryWatcher:230               "/mnt/MUSIC/Music/Donna Burke/" subdir path 
22:16:02.597 DEBUG LibraryWatcher:231               "/mnt/MUSIC/Music/Donna Burke/"  subdirectory path  

Thread 6 "QThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcefdf700 (LWP 19196)]
0x00007ffff01633a6 in vfprintf () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff01633a6 in vfprintf () at /usr/lib/libc.so.6
#1  0x00007ffff0166396 in buffered_vfprintf () at /usr/lib/libc.so.6
#2  0x00007ffff016370e in vfprintf () at /usr/lib/libc.so.6
#3  0x00007ffff016bf24 in fprintf () at /usr/lib/libc.so.6
#4  0x0000555556002e4d in logging::MessageHandler(QtMsgType, char const*) (type=QtDebugMsg, message=0x7fff7e9a6678 "__logging_message__22:16:02.597 DEBUG LibraryWatcher:230", ' ' <repeats 15 times>, "\"/mnt/MUSIC/Music/Donna Burke/\" subdir path ") at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/ext/libclementine-common/core/logging.cpp:74
#5  0x00007ffff645baa6 in qt_message_output(QtMsgType, char const*) () at /usr/lib/libQtCore.so.4
#6  0x0000555555aa0cac in QDebug::~QDebug() (this=0x7fffce7e2e50, __in_chrg=<optimized out>) at /usr/include/qt4/QtCore/qdebug.h:85
#7  0x0000555555ba384a in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:230
#8  0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#9  0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#10 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#11 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#12 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#13 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#14 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#15 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#16 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#17 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#18 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#19 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#20 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#21 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#22 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#23 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#24 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#25 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#26 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#27 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#28 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#29 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#30 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#31 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#32 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#33 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424
#34 0x0000555555ba4ad8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) (this=0x555556f893d0, path=..., subdir=..., t=0x7fffcefde680, force_noincremental=true)
    at /run/media/tazy/Data/Code/Clementine-1.3.1/Clementine/src/library/librarywatcher.cpp:424

\


void LibraryWatcher::ScanSubdirectory(const QString& path,
                                      const Subdirectory& subdir,
                                      ScanTransaction* t,
                                      bool force_noincremental) {
  QFileInfo path_info(path);
  QDir      path_dir(path);
  qLog(Debug) << path << "subdir path";
  qLog(Debug) << subdir.path << " subdirectory path " ;

**Comment by Tazmain** [comment]
$ cd 《动感新势力》/

**Comment by Tazmain** [comment]
renaming that folder makes sure the crash does not happen , the recursion is the cause
