### ISSUE TITLE
Clementine crashes under Wayland

### ISSUE THREAD

**Issue by JacobHenner** [clementine-player/Clementine#6595]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [X] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux
- Clementine version: Clementine 1.4.0rc1-128-ge1c872666

### Expected behaviour / actual behaviour

Expected: Clementine runs and remains open.

Actual: Clementine crashes with the following error message: 
`__logging_message__19:50:54.543 ERROR unknown                          The Wayland connection broke. Did the Wayland compositor die?`

This is on Arch, using the latest available qt5-wayland, running inside of GNOME. I've tried to reproduce this using other qt5 applications running in the same environment, and they have not crashed.

I haven't been able to narrow the crash down to a specific trigger, but I have noticed it has happened twice after Clementine has lost focus, and I've switched back to it with Alt-Tab.

### Steps to reproduce the problem (only for bugs)

Open Clementine in Wayland under GNOME, wait for Clementine to crash.

**Comment by JacobHenner** [comment]
To be clear, this is a separate issue than the one described at https://github.com/clementine-player/Clementine/issues/6587

**Comment by jbroadus** [comment]
How long does it usually take to crash? I built an Arch VM running gdm+Gnome on Wayland, but haven't seen this yet. Is there anything interesting directly before the error message?

**Comment by JacobHenner** [comment]
It varies, but most of the time it's been after the window loses and regains focus. It's also happened after returning from the GNOME lock screen. There is nothing relevant before the error message.

**Comment by jbroadus** [comment]
Still haven't seen this. Have you looked to see if wayland is logging anything when this happens? You could also look at dmesg or your audit log to see if an LSM is blocking something.

**Comment by JacobHenner** [comment]
I'll take a look and report back.

**Comment by JacobHenner** [comment]
Here's a backtrace:

```
Stack trace of thread 5924:
#0  0x00007fa97cac0ce5 raise (libc.so.6 + 0x3bce5)
#1  0x00007fa97caaa857 abort (libc.so.6 + 0x25857)
#2  0x000055f07e0881a8 n/a (clementine + 0x2ff1a8)
#3  0x00007fa97f6b3ad8 n/a (libQt5Core.so.5 + 0xc1ad8)
#4  0x00007fa97f6b3bea n/a (libQt5Core.so.5 + 0xc1bea)
#5  0x00007fa97f680952 _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5 + 0x8e952)
#6  0x00007fa9740a9128 n/a (libQt5WaylandClient.so.5 + 0x54128)
#7  0x00007fa9740b9b51 _ZN15QtWaylandClient15QWaylandDisplay13flushRequestsEv (libQt5WaylandClient.so.5 + 0x64b51)
#8  0x00007fa97f8cd540 n/a (libQt5Core.so.5 + 0x2db540)
#9  0x00007fa97f8d0d62 _ZN15QSocketNotifier9activatedEiNS_14QPrivateSignalE (libQt5Core.so.5 + 0x2ded62)
#10 0x00007fa97f8d10b2 _ZN15QSocketNotifier5eventEP6QEvent (libQt5Core.so.5 + 0x2df0b2)
#11 0x00007fa97da63362 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15b362)
#12 0x00007fa97da6c819 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x164819)
#13 0x00007fa97f897a12 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2a5a12)
#14 0x00007fa97f8f0cd6 n/a (libQt5Core.so.5 + 0x2fecd6)
#15 0x00007fa97eb229be g_main_context_dispatch (libglib-2.0.so.0 + 0x6b9be)
#16 0x00007fa97eb24831 n/a (libglib-2.0.so.0 + 0x6d831)
#17 0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#18 0x00007fa97f8f00d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
#19 0x00007fa97f89657c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
#20 0x00007fa97f89e586 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2ac586)
#21 0x000055f07e093b3a main (clementine + 0x30ab3a)
#22 0x00007fa97caac023 __libc_start_main (libc.so.6 + 0x27023)
#23 0x000055f07e09debe _start (clementine + 0x314ebe)

Stack trace of thread 5933:
#0  0x00007fa97cb79abf __poll (libc.so.6 + 0xf4abf)
#1  0x00007fa97eb247a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
#2  0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#3  0x00007fa97f8f00d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
#4  0x00007fa97f89657c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
#5  0x00007fa97f6bae62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e62)
#6  0x00007fa97f6bbfd6 n/a (libQt5Core.so.5 + 0xc9fd6)
#7  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#8  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5930:
#0  0x00007fa97cb79abf __poll (libc.so.6 + 0xf4abf)
#1  0x00007fa97eb247a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
#2  0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#3  0x00007fa97f8f00d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
#4  0x00007fa97f89657c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
#5  0x00007fa97f6bae62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e62)
#6  0x00007fa97f2f1b28 n/a (libQt5DBus.so.5 + 0x15b28)
#7  0x00007fa97f6bbfd6 n/a (libQt5Core.so.5 + 0xc9fd6)
#8  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#9  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5928:
#0  0x00007fa97e5eecf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
#1  0x00007fa9734b3e1c n/a (i965_dri.so + 0x4f8e1c)
#2  0x00007fa9734b3a18 n/a (i965_dri.so + 0x4f8a18)
#3  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#4  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5949:
#0  0x00007fa97cb79abf __poll (libc.so.6 + 0xf4abf)
#1  0x00007fa97eb247a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
#2  0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#3  0x00007fa97f8f00d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
#4  0x00007fa97f89657c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
#5  0x00007fa97f6bae62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e62)
#6  0x00007fa97f6bbfd6 n/a (libQt5Core.so.5 + 0xc9fd6)
#7  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#8  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5925:
#0  0x00007fa97e5eecf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
#1  0x00007fa9734b3e1c n/a (i965_dri.so + 0x4f8e1c)
#2  0x00007fa9734b3a18 n/a (i965_dri.so + 0x4f8a18)
#3  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#4  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5932:
#0  0x00007fa97cb79abf __poll (libc.so.6 + 0xf4abf)
#1  0x00007fa97eb247a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
#2  0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#3  0x00007fa97f8f00d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
#4  0x00007fa97f89657c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
#5  0x00007fa97f6bae62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e62)
#6  0x00007fa97f6bbfd6 n/a (libQt5Core.so.5 + 0xc9fd6)
#7  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#8  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5951:
#0  0x00007fa97cb79abf __poll (libc.so.6 + 0xf4abf)
#1  0x00007fa97eb247a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
#2  0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#3  0x00007fa97f8f00d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
#4  0x00007fa97f89657c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
#5  0x00007fa97f6bae62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e62)
#6  0x00007fa97f6bbfd6 n/a (libQt5Core.so.5 + 0xc9fd6)
#7  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#8  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5926:
#0  0x00007fa97e5eecf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
#1  0x00007fa9734b3e1c n/a (i965_dri.so + 0x4f8e1c)
#2  0x00007fa9734b3a18 n/a (i965_dri.so + 0x4f8a18)
#3  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#4  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5952:
#0  0x00007fa97cb79abf __poll (libc.so.6 + 0xf4abf)
#1  0x00007fa97eb247a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
#2  0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#3  0x00007fa97eb248c2 n/a (libglib-2.0.so.0 + 0x6d8c2)
#4  0x00007fa97eafbe71 n/a (libglib-2.0.so.0 + 0x44e71)
#5  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#6  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5927:
#0  0x00007fa97e5eecf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
#1  0x00007fa9734b3e1c n/a (i965_dri.so + 0x4f8e1c)
#2  0x00007fa9734b3a18 n/a (i965_dri.so + 0x4f8a18)
#3  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#4  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5953:
#0  0x00007fa97cb79abf __poll (libc.so.6 + 0xf4abf)
#1  0x00007fa97eb247a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
#2  0x00007fa97eb25843 g_main_loop_run (libglib-2.0.so.0 + 0x6e843)
#3  0x00007fa97ee54de8 n/a (libgio-2.0.so.0 + 0x59de8)
#4  0x00007fa97eafbe71 n/a (libglib-2.0.so.0 + 0x44e71)
#5  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#6  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5936:
#0  0x00007fa97cb79abf __poll (libc.so.6 + 0xf4abf)
#1  0x00007fa97eb247a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
#2  0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#3  0x00007fa97f8f00d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
#4  0x00007fa97f89657c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
#5  0x00007fa97f6bae62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e62)
#6  0x00007fa97f6bbfd6 n/a (libQt5Core.so.5 + 0xc9fd6)
#7  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#8  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5929:
#0  0x00007fa97cb79abf __poll (libc.so.6 + 0xf4abf)
#1  0x00007fa97eb247a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
#2  0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#3  0x00007fa97f8f00d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
#4  0x00007fa97f89657c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
#5  0x00007fa97f6bae62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e62)
#6  0x00007fa97f6bbfd6 n/a (libQt5Core.so.5 + 0xc9fd6)
#7  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#8  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5948:
#0  0x00007fa97cb79abf __poll (libc.so.6 + 0xf4abf)
#1  0x00007fa97eb247a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
#2  0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#3  0x00007fa97f8f00d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
#4  0x00007fa97f89657c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
#5  0x00007fa97f6bae62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e62)
#6  0x00007fa97f6bbfd6 n/a (libQt5Core.so.5 + 0xc9fd6)
#7  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#8  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5950:
#0  0x00007fa97cb79abf __poll (libc.so.6 + 0xf4abf)
#1  0x00007fa97eb247a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
#2  0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#3  0x00007fa97f8f00d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
#4  0x00007fa97f89657c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
#5  0x00007fa97f6bae62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e62)
#6  0x00007fa97f6bbfd6 n/a (libQt5Core.so.5 + 0xc9fd6)
#7  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#8  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5934:
#0  0x00007fa97cb79abf __poll (libc.so.6 + 0xf4abf)
#1  0x00007fa97eb247a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
#2  0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#3  0x00007fa97f8f00d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
#4  0x00007fa97f89657c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
#5  0x00007fa97f6bae62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e62)
#6  0x00007fa97f6bbfd6 n/a (libQt5Core.so.5 + 0xc9fd6)
#7  0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#8  0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)

Stack trace of thread 5935:
#0  0x00007fa97cb74d7e statx (libc.so.6 + 0xefd7e)
#1  0x00007fa97f82fa31 n/a (libQt5Core.so.5 + 0x23da31)
#2  0x00007fa97f7c9ced _ZNK9QFileInfo9isSymLinkEv (libQt5Core.so.5 + 0x1d7ced)
#3  0x000055f07e1a6fa7 _ZN14LibraryWatcher16ScanSubdirectoryERK7QStringRK12SubdirectoryPNS_15ScanTransactionEb (clementine + 0x41dfa7)
#4  0x000055f07e1a8166 _ZN14LibraryWatcher12AddDirectoryERK9DirectoryRK5QListI12SubdirectoryE (clementine + 0x41f166)
#5  0x000055f07e395ea2 n/a (clementine + 0x60cea2)
#6  0x00007fa97f8c530a _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2d330a)
#7  0x00007fa97da63362 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15b362)
#8  0x00007fa97da6c819 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x164819)
#9  0x00007fa97f897a12 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2a5a12)
#10 0x00007fa97f89a276 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2a8276)
#11 0x00007fa97f8f0a84 n/a (libQt5Core.so.5 + 0x2fea84)
#12 0x00007fa97eb229be g_main_context_dispatch (libglib-2.0.so.0 + 0x6b9be)
#13 0x00007fa97eb24831 n/a (libglib-2.0.so.0 + 0x6d831)
#14 0x00007fa97eb24871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
#15 0x00007fa97f8f00d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
#16 0x00007fa97f89657c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
#17 0x00007fa97f6bae62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e62)
#18 0x00007fa97f6bbfd6 n/a (libQt5Core.so.5 + 0xc9fd6)
#19 0x00007fa97e5e846f start_thread (libpthread.so.0 + 0x946f)
#20 0x00007fa97cb843d3 __clone (libc.so.6 + 0xff3d3)
```

Still looking for additional logs.

**Comment by Houndie** [comment]
Just wanted to confirm that this is still an issue.  v1.4 rc1, running sway under arch linux.

**Comment by CodedBinary** [comment]
Still an issue on arch/sway. I have never observed this occur without focusing on the window. It seems like after an hour or so of not focusing the window, the program crashes upon focusing. Using clementine 1.4.0rc1+347+gfc4cb6fc7-1 on the arch repos. Running clementine with --verbose still gives no more useful information. The following are the only error messages I saw.

`
03:26:21.508 ERROR logging:66(GLib)                 Source ID 12 was not found when attempting to remove it
03:48:19.193 ERROR unknown                          The Wayland connection broke. Did the Wayland compositor die?
`

**Comment by soulsource** [comment]
By chance I managed to get a better readable stack trace:
```
#0  0x00007fc211003d21 in raise () at /lib64/libc.so.6
#1  0x00007fc210fed536 in abort () at /lib64/libc.so.6
#2  0x000055d1b9b6dbdb in  ()
#3  0x00007fc2132f9178 in  () at /usr/lib64/libQt5Core.so.5
#4  0x00007fc2132f9299 in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007fc2132c5da8 in QMessageLogger::fatal(char const*, ...) const () at /usr/lib64/libQt5Core.so.5
#6  0x00007fc20abcee23 in  () at /usr/lib64/libQt5WaylandClient.so.5
#7  0x00007fc20abe03f4 in QtWaylandClient::QWaylandDisplay::flushRequests() ()
    at /usr/lib64/libQt5WaylandClient.so.5
#8  0x00007fc2134f3060 in  () at /usr/lib64/libQt5Core.so.5
#9  0x00007fc2134f67b6 in QSocketNotifier::activated(QSocketDescriptor, QSocketNotifier::Type, QSocketNotifier::QPrivateSignal) () at /usr/lib64/libQt5Core.so.5
#10 0x00007fc2134f6f2b in QSocketNotifier::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#11 0x00007fc211f50193 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib64/libQt5Widgets.so.5
#12 0x00007fc211f59210 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#13 0x00007fc2134be11f in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib64/libQt5Core.so.5
#14 0x00007fc2135163fe in  () at /usr/lib64/libQt5Core.so.5
#15 0x00007fc213030b79 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#16 0x00007fc213031098 in  () at /usr/lib64/libglib-2.0.so.0
#17 0x00007fc21303112f in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#18 0x00007fc213515ae0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib64/libQt5Core.so.5
#19 0x00007fc2134bcefb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib64/libQt5Core.so.5
#20 0x00007fc2134c51fd in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#21 0x000055d1b9b6f002 in main ()
```

**Comment by jbroadus** [comment]
@soulsource Are you also using Arch+Gnome?

**Comment by soulsource** [comment]
Nope, Gentoo and Sway.
I'm planning to do a rebuild of Clementine with Debug Symbols btw., to get maybe more info out.

**Comment by soulsource** [comment]
I've been trying the "changing stuff and seeing what happens" approach to debug this issue further.

Since the crash is random, I can't guarantee anything, but it seems to me that https://github.com/qt/qtwayland/commit/16760280fd04cf70255bab16d9acecad254fdd8f fixes the issue.

**Comment by bam80** [comment]
Possibly related, Fedora and Gnome:
https://github.com/KDAB/Charm/issues/364

**Comment by h-2** [comment]
I can confirm this crash. Running on Ubuntu 21.10 and Sway. Almost always when I switch the virtual desktop back to the desktop where Clementine is running, it crashes. It never crashes in the background and it never crashes when switching away -- only when switching back.
This makes the application somewhat unusable.
