### ISSUE TITLE
[1.4.0rc2] BUG choosing psychedelic colors crashes the app

### ISSUE THREAD

**Issue by mohicanb** [clementine-player/Clementine#6749]
### Before posting
- [X] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved

### System information
- Operating System: Linux Mint Xfce 20.0
- Clementine version: version 1.4.0-rc2 from Flathub.

## Steps to reproduce the problem (only for bugs)
In the sonograph menu, clic on the "psychedelic colors" : instant crash. Reproducible.

**Comment by jbroadus** [comment]
```
#0  0x00007ffff4d4d605 in raise () at /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff4d36899 in abort () at /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x0000555555dd216d in std::__replacement_assert(char const*, int, char const*, char const*)
    (__condition=0x555556778fc0 "__builtin_expect(__n < this->size(), true)", __function=0x5555567795f0 "std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = float; _Alloc = std::allocator<float>; std::vector<_Tp, _Alloc>::c"..., __line=1060, __file=0x555556779110 "/usr/include/c++/9.2.0/bits/stl_vector.h")
    at /usr/include/c++/9.2.0/x86_64-unknown-linux-gnu/bits/c++config.h:463
#3  0x0000555555dd216d in std::vector<float, std::allocator<float> >::operator[](unsigned long) const (__n=99, this=0x5555571f3ad8) at /usr/include/c++/9.2.0/bits/stl_vector.h:1060
#4  0x0000555555dd216d in Analyzer::Base::getPsychedelicColor(std::vector<float, std::allocator<float> > const&, int, int)
    (this=this@entry=0x5555571f38e0, scope=std::vector of length 99, capacity 99 = {...}, ampFactor=ampFactor@entry=10, bias=bias@entry=75) at ../src/analyzers/analyzerbase.cpp:230
#5  0x0000555555c163f8 in BlockAnalyzer::paletteChange(QPalette const&) (this=this@entry=0x5555571f38e0) at ../src/analyzers/blockanalyzer.cpp:343
#6  0x0000555555c15de3 in BlockAnalyzer::psychedelicModeChanged(bool) (this=0x5555571f38e0, enabled=<optimized out>) at ../src/analyzers/blockanalyzer.cpp:241
#7  0x0000555555c12f62 in AnalyzerContainer::TogglePsychedelicColors() (this=0x55555714a560) at ../src/analyzers/analyzercontainer.cpp:152
#8  0x00007ffff772c6f0 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff5d3eb32 in QAction::triggered(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff5d41158 in QAction::activate(QAction::ActionEvent) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff5ec6322 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff5ecd9aa in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff5ece9d2 in QMenu::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff5d877fe in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff5ed0fb3 in QMenu::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff5d44d2f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff5d4e0b3 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff76f7982 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff5d4d1a3 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff5da3124 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff5da5664 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff5d44d2f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff5d4de60 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff76f7982 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff5647053 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007ffff56486e5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007ffff562159b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#28 0x00007ffff070ae7a in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#29 0x00007ffff6d7a033 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff6d7a2c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff6d7a363 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff774e8be in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff76f651b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff76fe2f2 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00005555558bc8a8 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:461
```

**Comment by jbroadus** [comment]
I wish I understood the original intention here, but we're always reading one element past the end of the scope vector.

```
void Analyzer::Base::updateBandSize(const int scopeSize) {
  // prevent possible dbz in BandFrequency
  if (scopeSize == 0) {
    return;
  }

  bands_ = scopeSize;

  barkband_table_.clear();

  int barkband = 0;
  for (int i = 0; i < bands_ + 1; ++i) {
    if (barkband < sBarkBandCount - 1 &&
        BandFrequency(i) >= sBarkBands[barkband]) {
      barkband++;
    }

    barkband_table_.append(barkband);
  }
}

QColor Analyzer::Base::getPsychedelicColor(const Scope& scope,
                                           const int ampFactor,
                                           const int bias) {
  if (scope.size() > barkband_table_.size()) {
    return palette().color(QPalette::Highlight);
  }

  // Calculate total magnitudes for different bark bands.
  double bands[sBarkBandCount]{};

  for (int i = 0; i < barkband_table_.size(); ++i) {
    bands[barkband_table_[i]] += scope[i];
  }

  // Now divide the bark bands into thirds and compute their total amplitudes.
  double rgb[3]{};
  for (int i = 0; i < sBarkBandCount - 1; ++i) {
    rgb[(i * 3) / sBarkBandCount] += pow(bands[i], 2);
  }

  for (int i = 0; i < 3; ++i) {
    // bias colours for a threshold around normally amplified audio
    rgb[i] = qMin(255, (int)((sqrt(rgb[i]) * ampFactor) + bias));
  }

  return QColor::fromRgb(rgb[0], rgb[1], rgb[2]);
}
```

**Comment by mohicanb** [comment]
I confirm that this bug occurs with the 1.4.0-rc2 Flatpak.
It does NOT occur with the 1.4.0-rc1 from the Ubuntu depository.

**Comment by jbroadus** [comment]
Should be fixed now, but I'm not sure who maintains the flatpak. I think it was just luck that this wasn't occurring elsewhere.
