### ISSUE TITLE
clementine-remote no longer works after a system update

### ISSUE THREAD

**Issue by KruyKaze** [clementine-player/Clementine#6893]
Hello, 
I recently updated my Arch build and clementine remote stopped working . 

Clementine version:

> community/clementine 1.4.0rc1+347+gfc4cb6fc7-1 (4.9 MiB 17.6 MiB) (Installed)

Here's the output of the error:

```
clementine-remote -s <hidden> -p <hidden> -r play                                                                                                                                                            19:05:57 
Traceback (most recent call last):
  File "/usr/bin/clementine-remote", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-clementine-remote==1.0.3' distribution was not found and is required by the application

```
Please let me know if you need further info
Thank you!

**Comment by jbroadus** [comment]
This is actually not part of the clementine project: https://github.com/jjmontesl/python-clementine-remote

But a wild guess is that you updated from python 3.8 to 3.9 and the modules are still in the old location. You might try reinstalling the package or installing using pip.

**Comment by KruyKaze** [comment]
I had installed a long time ago and forgot that it was not part of clementine.
But that was exactly it . Thank you very much closing.
